-- MySQL Script generated by MySQL Workbench
-- Wed May 10 13:31:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_dados_pessoais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_dados_pessoais
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_dados_pessoais` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_dados_pessoais` ;

-- -----------------------------------------------------
-- Table `bd_dados_pessoais`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_dados_pessoais`.`endereco` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LOGRADOURO` VARCHAR(256) NOT NULL,
  `NUMERO` INT NOT NULL,
  `CEP` INT NOT NULL,
  `BAIRRO` VARCHAR(50) NOT NULL,
  `CIDADE` VARCHAR(30) NOT NULL,
  `ESTADO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_dados_pessoais`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_dados_pessoais`.`pessoa` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(256) NOT NULL,
  `CPF` INT NOT NULL,
  `ENDERECO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PESSOA_ENDERECO_idx` (`ENDERECO` ASC) VISIBLE,
  CONSTRAINT `FK_PESSOA_ENDERECO`
    FOREIGN KEY (`ENDERECO`)
    REFERENCES `bd_dados_pessoais`.`endereco` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_dados_pessoais`.`telefone_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_dados_pessoais`.`telefone_tipo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_dados_pessoais`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_dados_pessoais`.`telefone` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL,
  `DDD` INT NOT NULL,
  `TIPO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_TIPOTELEFONE_idx` (`TIPO` ASC) VISIBLE,
  CONSTRAINT `FK_TIPOTELEFONE`
    FOREIGN KEY (`TIPO`)
    REFERENCES `bd_dados_pessoais`.`telefone_tipo` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_dados_pessoais`.`pessoa_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_dados_pessoais`.`pessoa_telefone` (
  `ID_PESSOA` INT NOT NULL,
  `ID_TELEFONE` INT NOT NULL,
  PRIMARY KEY (`ID_PESSOA`, `ID_TELEFONE`),
  INDEX `FK_TELEFONE_idx` (`ID_TELEFONE` ASC) VISIBLE,
  CONSTRAINT `FK_PESSOA`
    FOREIGN KEY (`ID_PESSOA`)
    REFERENCES `bd_dados_pessoais`.`pessoa` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TELEFONE`
    FOREIGN KEY (`ID_TELEFONE`)
    REFERENCES `bd_dados_pessoais`.`telefone` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
